# Generated by Django 5.0.2 on 2024-03-20 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True)),
                ('mahsulot_id', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='missed_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Xatolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True)),
                ('xato_id', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Missed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xato_soni', models.PositiveIntegerField(default=0)),
                ('butun_soni', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('ish_vaqti', models.PositiveIntegerField(null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='missed_audio/')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_mahsulot', to='Post.mahsulot')),
            ],
        ),
    ]
