# Generated by Django 5.0.2 on 2024-03-20 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Post', '0001_initial'),
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='missed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missed',
            name='xodim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_xodim', to='User.xodim'),
        ),
        migrations.AddField(
            model_name='missed',
            name='photo',
            field=models.ManyToManyField(related_name='missed_photo', to='Post.photo'),
        ),
        migrations.AddField(
            model_name='missed',
            name='xato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_xato', to='Post.xatolar'),
        ),
    ]
