# Generated by Django 5.0.2 on 2024-03-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_xodim',
            field=models.BooleanField(default=False),
        ),
    ]
