# Generated by Django 5.0.2 on 2024-03-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_is_xodim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_xodim',
            field=models.BooleanField(default=True),
        ),
    ]
