# Generated by Django 5.0.2 on 2024-03-20 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_is_xodim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodim',
            name='bulimi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xodim_bulim', to='User.bulim'),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='ish_turi',
            field=models.ManyToManyField(null=True, related_name='xodim_ish_turi', to='User.ish_turi'),
        ),
    ]
