# Generated by Django 5.0.2 on 2024-03-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_xodim_bulimi_alter_xodim_ish_turi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodim',
            name='ish_turi',
            field=models.ManyToManyField(related_name='xodim_ish_turi', to='User.ish_turi'),
        ),
    ]
