# Generated by Django 5.0.2 on 2024-03-21 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_xodim_ish_turi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodim',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xodim_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
